"""Classification registry for all ``/api/v1`` HTTP routes.

This registry is intentionally explicit.
Anti-drift tests compare it against the live FastAPI router so new
``/api/v1`` routes must be classified deliberately.
"""

from __future__ import annotations

from typing import Final, Literal, TypeAlias

RouteCategory: TypeAlias = Literal[
    "config_mutation",
    "data_mutation",
    "read_live",
    "read_history",
    "public",
]

RouteSignature: TypeAlias = tuple[str, str]

PUBLIC_ROUTE_ALLOWLIST: Final[frozenset[RouteSignature]] = frozenset(
    {
        ("GET", "/api/v1/system/health"),
    }
)

ROUTE_CLASSIFICATIONS: Final[dict[RouteSignature, RouteCategory]] = {
    ("DELETE", "/api/v1/adapters/instances/{instance_id}"): "config_mutation",
    ("DELETE", "/api/v1/auth/apikeys/{key_id}"): "config_mutation",
    ("DELETE", "/api/v1/auth/users/{username}"): "config_mutation",
    ("DELETE", "/api/v1/auth/users/{username}/mqtt-password"): "config_mutation",
    ("DELETE", "/api/v1/config/autobackup/{name}"): "config_mutation",
    ("DELETE", "/api/v1/config/reset"): "config_mutation",
    ("DELETE", "/api/v1/config/reset/adapters"): "config_mutation",
    ("DELETE", "/api/v1/config/reset/bindings"): "config_mutation",
    ("DELETE", "/api/v1/config/reset/datapoints"): "config_mutation",
    ("DELETE", "/api/v1/config/reset/logic"): "config_mutation",
    ("DELETE", "/api/v1/datapoints/{dp_id}"): "config_mutation",
    ("DELETE", "/api/v1/datapoints/{dp_id}/bindings/{binding_id}"): "config_mutation",
    ("DELETE", "/api/v1/hierarchy/links"): "config_mutation",
    ("DELETE", "/api/v1/hierarchy/nodes/{node_id}"): "config_mutation",
    ("DELETE", "/api/v1/hierarchy/trees/{tree_id}"): "config_mutation",
    ("DELETE", "/api/v1/icons/"): "config_mutation",
    ("DELETE", "/api/v1/knx/keyfile/{file_id}"): "config_mutation",
    ("DELETE", "/api/v1/knxproj/group-addresses"): "config_mutation",
    ("DELETE", "/api/v1/logic/graphs/{graph_id}"): "config_mutation",
    ("DELETE", "/api/v1/message-archives/{archive_id}"): "config_mutation",
    ("DELETE", "/api/v1/ringbuffer/filtersets/{filterset_id}"): "config_mutation",
    ("POST", "/api/v1/ringbuffer/migration/decision"): "config_mutation",
    ("POST", "/api/v1/ringbuffer/migration/start"): "config_mutation",
    ("DELETE", "/api/v1/security/url-target-allowlist"): "config_mutation",
    ("DELETE", "/api/v1/support/debug-log"): "config_mutation",
    ("DELETE", "/api/v1/system/nav-links/{link_id}"): "config_mutation",
    ("DELETE", "/api/v1/visu/backgrounds"): "config_mutation",
    ("DELETE", "/api/v1/visu/nodes/{node_id}"): "config_mutation",
    ("GET", "/api/v1/adapters/"): "read_live",
    ("GET", "/api/v1/adapters/instances"): "read_live",
    ("GET", "/api/v1/adapters/instances/{instance_id}"): "read_live",
    ("GET", "/api/v1/adapters/instances/{instance_id}/anwesenheit/datapoints"): "read_live",
    ("GET", "/api/v1/adapters/instances/{instance_id}/anwesenheit/health"): "read_live",
    ("GET", "/api/v1/adapters/instances/{instance_id}/bindings"): "read_live",
    ("GET", "/api/v1/adapters/instances/{instance_id}/holidays"): "read_live",
    ("GET", "/api/v1/adapters/instances/{instance_id}/iobroker/states"): "read_live",
    ("GET", "/api/v1/adapters/instances/{instance_id}/mqtt/browse"): "read_live",
    ("GET", "/api/v1/adapters/instances/{instance_id}/mqtt/sample"): "read_live",
    ("GET", "/api/v1/adapters/instances/{instance_id}/snmp/walk"): "read_live",
    ("GET", "/api/v1/adapters/knx/dpts"): "read_live",
    ("GET", "/api/v1/adapters/{adapter_type}/binding-schema"): "read_live",
    ("GET", "/api/v1/adapters/{adapter_type}/config"): "read_live",
    ("GET", "/api/v1/adapters/{adapter_type}/schema"): "read_live",
    ("GET", "/api/v1/auth/apikeys"): "read_live",
    ("GET", "/api/v1/auth/me"): "read_live",
    ("GET", "/api/v1/auth/users"): "read_live",
    ("GET", "/api/v1/auth/users/{username}"): "read_live",
    ("GET", "/api/v1/camera/proxy"): "read_live",
    ("GET", "/api/v1/config/autobackup/config"): "read_live",
    ("GET", "/api/v1/config/autobackup/list"): "read_live",
    ("GET", "/api/v1/config/export"): "read_live",
    ("GET", "/api/v1/config/export/db"): "read_live",
    ("GET", "/api/v1/datapoints/"): "read_live",
    ("GET", "/api/v1/datapoints/tags"): "read_live",
    ("GET", "/api/v1/datapoints/{dp_id}"): "read_live",
    ("GET", "/api/v1/datapoints/{dp_id}/bindings"): "read_live",
    ("GET", "/api/v1/datapoints/{dp_id}/knx-context"): "read_live",
    ("GET", "/api/v1/datapoints/{dp_id}/value"): "read_live",
    ("GET", "/api/v1/hierarchy/datapoints/{dp_id}/nodes"): "read_live",
    ("GET", "/api/v1/hierarchy/nodes/search"): "read_live",
    ("GET", "/api/v1/hierarchy/nodes/{node_id}/datapoints"): "read_live",
    ("GET", "/api/v1/hierarchy/trees"): "read_live",
    ("GET", "/api/v1/hierarchy/trees/{tree_id}/nodes"): "read_live",
    ("GET", "/api/v1/history/{dp_id}"): "read_history",
    ("GET", "/api/v1/history/{dp_id}/aggregate"): "read_history",
    ("GET", "/api/v1/icons/"): "read_live",
    ("GET", "/api/v1/icons/settings"): "read_live",
    ("GET", "/api/v1/icons/{name}"): "read_live",
    ("GET", "/api/v1/knx/scan"): "read_live",
    ("GET", "/api/v1/knxproj/devices"): "read_live",
    ("GET", "/api/v1/knxproj/devices/{pa}"): "read_live",
    ("GET", "/api/v1/knxproj/devices/{pa}/datapoints"): "read_live",
    ("GET", "/api/v1/knxproj/group-addresses"): "read_live",
    ("GET", "/api/v1/knxproj/group-addresses/{ga:path}/devices"): "read_live",
    ("GET", "/api/v1/logic/datapoint/{dp_id}/usages"): "read_live",
    ("GET", "/api/v1/logic/graphs"): "read_live",
    ("GET", "/api/v1/logic/graphs/{graph_id}"): "read_live",
    ("GET", "/api/v1/logic/graphs/{graph_id}/export"): "read_live",
    ("GET", "/api/v1/logic/node-types"): "read_live",
    ("GET", "/api/v1/message-archives"): "read_history",
    ("GET", "/api/v1/message-archives/entries"): "read_history",
    ("GET", "/api/v1/message-archives/export/db"): "read_history",
    ("GET", "/api/v1/message-archives/{archive_id}"): "read_history",
    ("GET", "/api/v1/message-archives/{archive_id}/entries"): "read_history",
    ("GET", "/api/v1/message-archives/{archive_id}/export"): "read_history",
    ("GET", "/api/v1/ringbuffer/"): "read_live",
    ("GET", "/api/v1/ringbuffer/export/settings"): "read_live",
    ("GET", "/api/v1/ringbuffer/filtersets"): "read_live",
    ("GET", "/api/v1/ringbuffer/filtersets/{filterset_id}"): "read_live",
    ("GET", "/api/v1/ringbuffer/migration"): "read_history",
    ("GET", "/api/v1/ringbuffer/stats"): "read_history",
    ("GET", "/api/v1/search/"): "read_live",
    ("GET", "/api/v1/security/url-target-allowlist"): "read_live",
    ("GET", "/api/v1/support/categories"): "read_live",
    ("GET", "/api/v1/support/debug-log"): "read_live",
    ("GET", "/api/v1/system/adapters"): "read_live",
    ("GET", "/api/v1/system/datatypes"): "read_live",
    ("GET", "/api/v1/system/health"): "public",
    ("GET", "/api/v1/system/history/settings"): "read_live",
    ("GET", "/api/v1/system/log-level"): "read_live",
    ("GET", "/api/v1/system/logs"): "read_live",
    ("GET", "/api/v1/system/nav-links"): "read_live",
    ("GET", "/api/v1/system/settings"): "read_live",
    ("GET", "/api/v1/visu/backgrounds"): "read_live",
    ("GET", "/api/v1/visu/backgrounds/{name}"): "read_live",
    ("GET", "/api/v1/visu/nodes/{node_id}"): "read_live",
    ("GET", "/api/v1/visu/nodes/{node_id}/breadcrumb"): "read_live",
    ("GET", "/api/v1/visu/nodes/{node_id}/children"): "read_live",
    ("GET", "/api/v1/visu/nodes/{node_id}/export"): "read_live",
    ("GET", "/api/v1/visu/nodes/{node_id}/users"): "read_live",
    ("GET", "/api/v1/visu/pages/{node_id}"): "read_live",
    ("GET", "/api/v1/visu/tree"): "read_live",
    ("GET", "/api/v1/visu/widget-ref/{page_id}"): "read_live",
    ("GET", "/api/v1/weather/fetch"): "read_live",
    ("PATCH", "/api/v1/adapters/instances/{instance_id}"): "config_mutation",
    ("PATCH", "/api/v1/adapters/{adapter_type}/config"): "config_mutation",
    ("PATCH", "/api/v1/auth/users/{username}"): "config_mutation",
    ("PATCH", "/api/v1/datapoints/{dp_id}"): "config_mutation",
    ("PATCH", "/api/v1/datapoints/{dp_id}/bindings/{binding_id}"): "config_mutation",
    ("PATCH", "/api/v1/logic/graphs/{graph_id}"): "config_mutation",
    ("PATCH", "/api/v1/message-archives/{archive_id}"): "config_mutation",
    ("PATCH", "/api/v1/message-archives/{archive_id}/entries/{entry_id}"): "data_mutation",
    ("PATCH", "/api/v1/ringbuffer/filtersets/order"): "config_mutation",
    ("PATCH", "/api/v1/ringbuffer/filtersets/{filterset_id}/topbar"): "config_mutation",
    ("PATCH", "/api/v1/system/nav-links/{link_id}"): "config_mutation",
    ("PATCH", "/api/v1/visu/nodes/{node_id}"): "config_mutation",
    ("POST", "/api/v1/adapters/instances"): "config_mutation",
    ("POST", "/api/v1/adapters/instances/{instance_id}/anwesenheit/sync-bindings"): "config_mutation",
    ("POST", "/api/v1/adapters/instances/{instance_id}/iobroker/import"): "config_mutation",
    ("POST", "/api/v1/adapters/instances/{instance_id}/iobroker/import-preview"): "config_mutation",
    ("POST", "/api/v1/adapters/instances/{instance_id}/restart"): "config_mutation",
    ("POST", "/api/v1/adapters/instances/{instance_id}/test"): "config_mutation",
    ("POST", "/api/v1/adapters/instances/{source_instance_id}/bindings/migrate"): "config_mutation",
    ("POST", "/api/v1/adapters/{adapter_type}/test"): "config_mutation",
    ("POST", "/api/v1/auth/apikeys"): "config_mutation",
    ("POST", "/api/v1/auth/login"): "config_mutation",
    ("POST", "/api/v1/auth/me/change-password"): "config_mutation",
    ("POST", "/api/v1/auth/refresh"): "config_mutation",
    ("POST", "/api/v1/auth/users"): "config_mutation",
    ("POST", "/api/v1/auth/users/{username}/mqtt-password"): "config_mutation",
    ("POST", "/api/v1/config/autobackup/restore/{name}"): "config_mutation",
    ("POST", "/api/v1/config/autobackup/run"): "config_mutation",
    ("POST", "/api/v1/config/import"): "config_mutation",
    ("POST", "/api/v1/config/import/db"): "config_mutation",
    ("POST", "/api/v1/datapoints/"): "config_mutation",
    ("POST", "/api/v1/datapoints/{dp_id}/bindings"): "config_mutation",
    ("POST", "/api/v1/datapoints/{dp_id}/value"): "data_mutation",
    ("POST", "/api/v1/hierarchy/import-from-ets"): "config_mutation",
    ("POST", "/api/v1/hierarchy/links"): "config_mutation",
    ("POST", "/api/v1/hierarchy/nodes"): "config_mutation",
    ("POST", "/api/v1/hierarchy/trees"): "config_mutation",
    ("POST", "/api/v1/icons/export"): "config_mutation",
    ("POST", "/api/v1/icons/fontawesome"): "config_mutation",
    ("POST", "/api/v1/icons/import"): "config_mutation",
    ("POST", "/api/v1/icons/knxuf"): "config_mutation",
    ("POST", "/api/v1/knx/keyfile"): "config_mutation",
    ("POST", "/api/v1/knxproj/import"): "config_mutation",
    ("POST", "/api/v1/knxproj/import-csv"): "config_mutation",
    ("PUT", "/api/v1/knxproj/devices/{pa}/hierarchy-links"): "config_mutation",
    ("POST", "/api/v1/logic/graphs"): "config_mutation",
    ("POST", "/api/v1/logic/graphs/import"): "config_mutation",
    ("POST", "/api/v1/logic/graphs/validate"): "read_live",
    ("POST", "/api/v1/logic/graphs/{graph_id}/duplicate"): "config_mutation",
    ("POST", "/api/v1/logic/graphs/{graph_id}/run"): "config_mutation",
    ("POST", "/api/v1/message-archives"): "config_mutation",
    ("POST", "/api/v1/message-archives/import/db"): "config_mutation",
    ("POST", "/api/v1/message-archives/integrity-check"): "config_mutation",
    ("POST", "/api/v1/message-archives/{archive_id}/clear"): "config_mutation",
    ("POST", "/api/v1/message-archives/{archive_id}/entries"): "data_mutation",
    ("POST", "/api/v1/message-archives/{archive_id}/entries/{entry_id}/acknowledge"): "data_mutation",
    ("POST", "/api/v1/message-archives/{archive_id}/entries/{entry_id}/read"): "data_mutation",
    ("POST", "/api/v1/ringbuffer/config"): "config_mutation",
    ("POST", "/api/v1/ringbuffer/export/csv"): "read_history",
    ("POST", "/api/v1/ringbuffer/filtersets"): "config_mutation",
    ("POST", "/api/v1/ringbuffer/filtersets/export/count"): "read_history",
    ("POST", "/api/v1/ringbuffer/filtersets/export/csv"): "read_history",
    ("POST", "/api/v1/ringbuffer/filtersets/query"): "read_history",
    ("POST", "/api/v1/ringbuffer/filtersets/{filterset_id}/clone"): "config_mutation",
    ("POST", "/api/v1/ringbuffer/filtersets/{filterset_id}/query"): "read_history",
    ("POST", "/api/v1/ringbuffer/query"): "read_history",
    ("POST", "/api/v1/security/url-target-allowlist"): "config_mutation",
    ("POST", "/api/v1/security/url-target-check"): "read_live",
    ("POST", "/api/v1/support/debug-log"): "config_mutation",
    ("POST", "/api/v1/support/package"): "read_live",
    ("POST", "/api/v1/system/history/test"): "config_mutation",
    ("POST", "/api/v1/system/nav-links"): "config_mutation",
    ("POST", "/api/v1/visu/backgrounds/import"): "config_mutation",
    ("POST", "/api/v1/visu/nodes"): "config_mutation",
    ("POST", "/api/v1/visu/nodes/import"): "config_mutation",
    ("POST", "/api/v1/visu/nodes/{node_id}/auth"): "config_mutation",
    ("POST", "/api/v1/visu/nodes/{node_id}/copy"): "config_mutation",
    ("PUT", "/api/v1/config/autobackup/config"): "config_mutation",
    ("PUT", "/api/v1/hierarchy/nodes/{node_id}"): "config_mutation",
    ("PUT", "/api/v1/hierarchy/nodes/{node_id}/move"): "config_mutation",
    ("PUT", "/api/v1/hierarchy/trees/{tree_id}"): "config_mutation",
    ("PUT", "/api/v1/icons/settings"): "config_mutation",
    ("PUT", "/api/v1/logic/graphs/{graph_id}"): "config_mutation",
    ("PUT", "/api/v1/ringbuffer/export/settings"): "config_mutation",
    ("PUT", "/api/v1/ringbuffer/filtersets/{filterset_id}"): "config_mutation",
    ("PUT", "/api/v1/system/history/settings"): "config_mutation",
    ("PUT", "/api/v1/system/log-level"): "config_mutation",
    ("PUT", "/api/v1/system/settings"): "config_mutation",
    ("PUT", "/api/v1/visu/nodes/{node_id}/move"): "config_mutation",
    ("PUT", "/api/v1/visu/nodes/{node_id}/users"): "config_mutation",
    ("PUT", "/api/v1/visu/pages/{node_id}"): "config_mutation",
    ("WEBSOCKET", "/api/v1/ws"): "read_live",
}
