"""Node definition for the ``sensor_watchdog`` function block (Sensor Watchdog)."""

from __future__ import annotations

from obs.logic.models import NodeTypeDef

NODE_TYPE = NodeTypeDef(
    type="sensor_watchdog",
    label="Sensor Watchdog",
    category="timer",
    description=(
        "Überwacht bis zu 10 Eingänge auf das Ausbleiben neuer Telegramme. Pro Eingang müssen "
        "sowohl der Wert als auch der zugehörige Geändert-Ausgang des Read-Objekt-Blocks "
        "verbunden werden — nur ein neues Telegramm (Geändert=true) setzt den Timeout zurück, "
        "ein unverändert erneut gesendeter Wert zählt als Lebenszeichen, ein bloßes Neu-Auswerten "
        "des Graphen dagegen nicht. Bleibt ein Eingang länger als sein konfigurierter Timeout ohne "
        "neues Telegramm, wird sein Ausgang durch den konfigurierten Fault-Value ersetzt und "
        "einmalig ein Fehlertext samt Trigger ausgegeben; über die optionale Wiederholung kann der "
        "Trigger zusätzlich in einem festen Intervall erneut ausgelöst werden, solange der Eingang "
        "weiter ausbleibt. Arbeitet autonom über einen internen Scheduler — unabhängig davon, ob "
        "sonst irgendwo im Graphen ein Ereignis eintritt."
    ),
    # Dynamic — generated by the frontend from the length of the ``inputs`` config array
    # (in_1..in_N + in_1_changed..in_N_changed / out_1..out_N), plus the two fixed outputs below.
    inputs=[],
    outputs=[],
    config_schema={
        "inputs": {
            "type": "array",
            "label": "Überwachte Eingänge",
            "description": "Bis zu 10 Eingänge, je mit eigenem Timeout, Fault-Value und optionaler Wiederholung.",
            "items": {
                "type": "object",
                "required": ["timeout_s"],
                "properties": {
                    "label": {"type": "string", "default": "", "label": "Anzeigename"},
                    "timeout_s": {"type": "number", "default": 60, "min": 1, "label": "Timeout (Sekunden)"},
                    "fault_value": {"description": "Ersatzwert nach Ablauf des Timeouts.", "label": "Fault-Value"},
                    "repeat_s": {
                        "type": "number",
                        "default": 0,
                        "min": 0,
                        "label": "Wiederholung (Sekunden)",
                        "description": "0 = Fehlertrigger nur einmalig beim Auslösen. Sonst erneutes Auslösen im angegebenen Intervall, solange der Eingang weiter ausbleibt.",
                    },
                },
            },
            "default": [{"label": "", "timeout_s": 60, "fault_value": None, "repeat_s": 0}],
        },
    },
    color="#b45309",
    help_id="logic-block-timer-sensor-watchdog",
)
