from __future__ import annotations

from obs.logic.nodes.timer.sensor_watchdog import NODE_TYPE as SENSOR_WATCHDOG


def test_metadata():
    assert SENSOR_WATCHDOG.type == "sensor_watchdog"
    assert SENSOR_WATCHDOG.category == "timer"
    assert SENSOR_WATCHDOG.color.startswith("#")
    assert SENSOR_WATCHDOG.help_id == "logic-block-timer-sensor-watchdog"


def test_ports_are_fully_dynamic():
    # Generated by the frontend from the length of the "inputs" config array
    # (in_1..in_N / out_1..out_N plus fault_text/fault_trigger) — nothing static.
    assert SENSOR_WATCHDOG.inputs == []
    assert SENSOR_WATCHDOG.outputs == []


def test_inputs_config_schema_shape():
    schema = SENSOR_WATCHDOG.config_schema["inputs"]
    assert schema["type"] == "array"
    assert schema["items"]["type"] == "object"
    assert schema["items"]["required"] == ["timeout_s"]

    props = schema["items"]["properties"]
    assert props["timeout_s"]["default"] == 60
    assert props["timeout_s"]["min"] == 1
    assert props["label"]["default"] == ""
    assert "fault_value" in props
    assert props["repeat_s"]["default"] == 0
    assert props["repeat_s"]["min"] == 0


def test_default_has_exactly_one_entry():
    default = SENSOR_WATCHDOG.config_schema["inputs"]["default"]
    assert len(default) == 1
    assert default[0]["timeout_s"] == 60
    assert default[0]["repeat_s"] == 0
