#!/bin/sh
# SPDX-FileCopyrightText: 2026 abeggled and all contributors
# SPDX-License-Identifier: MIT
#
# obs-onewire-configure.sh — generates /etc/owfs.conf from OBS_ONEWIRE__*
# environment variables (populated by systemd's EnvironmentFile=/etc/obs.env
# on the LXC side, or Docker Compose's environment: on the sidecar side).
#
# Runs as ExecStartPre= on owserver.service (LXC) and as a step in the Docker
# sidecar entrypoint, on every start — the file is fully regenerated each
# time and is never meant to be edited by hand.
set -eu

conf=${OBS_ONEWIRE_CONF_PATH:-/etc/owfs.conf}

{
    echo "# Generated by obs-onewire-configure.sh — do not edit by hand."
    echo "server: port = ${OBS_ONEWIRE__PORT:-4304}"

    if [ "${OBS_ONEWIRE__USB_ALL:-}" = "true" ]; then
        echo "server: usb = all"
    fi

    if [ -n "${OBS_ONEWIRE__PBM_DEVICES:-}" ]; then
        old_ifs=$IFS
        IFS=','
        set -- $OBS_ONEWIRE__PBM_DEVICES
        IFS=$old_ifs
        for device in "$@"; do
            [ -n "$device" ] && echo "server: pbm = $device"
        done
    fi
} > "$conf"
